version: "3"

services:
  # --- Nodo Maestro de Hadoop (Namenode) ---
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"   # Interfaz Web de Hadoop
      - "9000:9000"   # Puerto de conexión interna

  # --- Nodo de Datos (Datanode) ---
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  # --- Cliente Pig 
  pig-client:
    build: 
      context: .
      dockerfile: Dockerfile.pig
    container_name: pig-client
    
    command: tail -f /dev/null 
    env_file:
      - ./hadoop.env
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      
      - ./:/app  
    depends_on:
      - namenode
      - datanode

# Volúmenes para persistir datos de Hadoop
volumes:
  hadoop_namenode:
  hadoop_datanode: